import {db} from '@/lib/server';import {NEWSLETTER_TEXT,RETENTION_TEXT,normalizePhone} from '@/lib/guest-consent';import {env} from 'cloudflare:workers';
export async function guestStatements(b:any,source:string){if(!b.saveGuest&&!b.newsletter)return [];const email=(b.email||'').trim().toLowerCase(),phone=normalizePhone(b.phone)||b.phone.trim();const contactKey=email?'email:'+email:'phone:'+phone;const existing=await db().prepare('SELECT * FROM guest_profiles WHERE contact_key=?').bind(contactKey).first();const now=Date.now();const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(contactKey));const id=existing?.id||Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,'0')).join('');const renew=b.newsletter&&(!existing||['none','unsubscribed'].includes(existing.newsletter)||existing.newsletter==='pending'&&now-existing.requested_at>7*86400000);const confirm=renew?crypto.randomUUID():existing?.confirm_token||crypto.randomUUID(),unsubscribe=existing?.unsubscribe_token||crypto.randomUUID(),status=renew?'pending':existing?.newsletter||'none';const requested=renew?now:existing?.requested_at||null;const statements=[db().prepare(`INSERT INTO guest_profiles(id,contact_key,name,phone,email,saved_at,updated_at,retention,newsletter,requested_at,confirm_token,unsubscribe_token) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(contact_key) DO UPDATE SET name=excluded.name,phone=excluded.phone,updated_at=excluded.updated_at,retention=MAX(guest_profiles.retention,excluded.retention),newsletter=CASE WHEN ? THEN CASE WHEN guest_profiles.newsletter='confirmed' THEN 'confirmed' ELSE excluded.newsletter END ELSE guest_profiles.newsletter END,requested_at=CASE WHEN ? AND guest_profiles.newsletter<>'confirmed' THEN excluded.requested_at ELSE guest_profiles.requested_at END,confirm_token=CASE WHEN ? AND guest_profiles.newsletter<>'confirmed' THEN excluded.confirm_token ELSE guest_profiles.confirm_token END`).bind(id,contactKey,b.name.trim(),phone,email,now,now,b.saveGuest?1:0,status,requested,confirm,unsubscribe,renew?1:0,renew?1:0,renew?1:0)];if(b.saveGuest&&!existing?.retention)statements.push(db().prepare('INSERT INTO consent_events(id,guest_id,event,time,text,source) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),id,'profile_saved',now,RETENTION_TEXT,source));if(renew){statements.push(db().prepare('INSERT INTO consent_events(id,guest_id,event,time,text,source) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),id,'newsletter_requested',now,NEWSLETTER_TEXT,source));const origin=(env as any).SITE_ORIGIN;const body=`Hallo ${b.name.trim()},

bitte bestätige hier, dass du Eventinfos und Aktionen von Paja’s per E-Mail erhalten möchtest:
${origin}/newsletter?token=${confirm}&action=confirm

Falls du dich nicht angemeldet hast, ignoriere diese Nachricht. Ohne Bestätigung bekommst du keine Eventinfos. Der Link gilt sieben Tage.

Paja’s Restaurant
Unterer Grasweg 25, 67065 Ludwigshafen
01577 2960906`;statements.push(db().prepare('INSERT INTO message_jobs(id,job_key,guest_id,kind,channel,recipient,subject,body,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),'doi:'+confirm,id,'doi','email',email,'Bitte bestätige deine Paja’s Eventinfos',body,now));}return statements;}
