"use client";
import {useState,useEffect} from 'react';
import {CalendarDays,Users,Clock,Check,Phone} from 'lucide-react';
import {de} from 'date-fns/locale';
import {Checkbox} from '@/components/ui/checkbox';
import {NEWSLETTER_TEXT,RETENTION_TEXT} from '@/lib/guest-consent';
import {Calendar} from '@/components/ui/calendar';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {berlinClock,localDate,dayKey,validDate,slotsFor,dateLabel} from '@/lib/reservations';
export default function Reservation(){const [open,setOpen]=useState(false),[step,setStep]=useState(1),[date,setDate]=useState<Date>(),[time,setTime]=useState(''),[guests,setGuests]=useState('2'),[contact,setContact]=useState({name:'',phone:'',note:'',email:'',saveGuest:false,newsletter:false,smsNotify:false}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[requestId,setRequestId]=useState(''),[result,setResult]=useState<any>(null),[now,setNow]=useState(new Date()),[messaging,setMessaging]=useState({email:false,sms:false});const key=date?dayKey(date):'',slots=key?slotsFor(key,now):[];
useEffect(()=>{fetch('/api/messaging-status').then(r=>r.json()).then((b:any)=>setMessaging(b)).catch(()=>{});setRequestId(crypto.randomUUID());setDate(localDate(berlinClock().date));const id=new URLSearchParams(location.search).get('reservierung');if(id){setResult({id,status:'angefragt'});setOpen(true);setStep(3)}const t=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(t)},[]);
useEffect(()=>{if(time&&!slots.includes(time))setTime('')},[key,now]);
useEffect(()=>{if(!result?.id)return;const load=async()=>{try{const r=await fetch('/api/reservations/'+result.id);const b:any=await r.json();if(!r.ok)throw new Error(b.error||'Status konnte nicht geladen werden.');setResult(b);setError('')}catch(e){setError((e as Error).message)}};load();const t=setInterval(load,10000);return()=>clearInterval(t)},[result?.id]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'start_table_reservation',description:'Öffnet das sichtbare Reservierungsformular. Sendet keine Anfrage und bestätigt keinen Tisch.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!input||Object.keys(input).length)throw new Error('Keine Eingaben erwartet');setOpen(true);return {action:'reservation_form_opened'}}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[]);
async function submit(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{const r=await fetch('/api/reservations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...contact,date:key,time,guests:Number(guests),requestId})});const b:any=await r.json();if(!r.ok)throw new Error(b.error||'Bitte erneut versuchen.');setResult({id:b.id,date:key,time,guests:Number(guests),status:'angefragt'});setStep(3);const url=new URL(location.href);url.searchParams.set('reservierung',b.id);history.replaceState(null,'',url);setRequestId(crypto.randomUUID())}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
function another(){setResult(null);setStep(1);setTime('');setContact({name:'',phone:'',note:'',email:'',saveGuest:false,newsletter:false,smsNotify:false});setError('');const u=new URL(location.href);u.searchParams.delete('reservierung');history.replaceState(null,'',u)}
return <section className="reservation-band" id="reservieren"><div className="wrap reservation-inner"><div><p className="eyebrow">WIR HALTEN DIR GERNE EINEN PLATZ FREI.</p><h2>Ein Tisch.<br/>Für eure gemeinsame Zeit.</h2><p>Zu zweit, mit Freunden oder mit der Familie: Sag uns, wann du kommen möchtest. Wir prüfen deine Anfrage und bestätigen deinen Tisch.</p></div><div className="reservation-invite"><div className="reservation-icons"><CalendarDays/><Users/><Clock/></div><h3>{result?'Deine Tischanfrage':'Wann sehen wir uns?'}</h3><p>Datum, Uhrzeit und Gästezahl wählen.<br/>Den Rest klären wir persönlich.</p><button className="button primary full" onClick={()=>{setOpen(true);setStep(result?3:1)}}>{result?'Tischanfrage ansehen':'Tisch reservieren'}</button><a href="tel:+4915772960906" className="reservation-phone"><Phone size={16}/>Für mehr als 12 Gäste: 01577 2960906</a></div></div>
<Dialog open={open} onOpenChange={setOpen}><DialogContent className="reservation-dialog"><div className="reservation-modal-head"><p className="eyebrow">DEIN PLATZ BEI PAJA’S</p><DialogTitle>{step===3?(result?.status==='bestätigt'?'Wir freuen uns auf euch.':result?.status==='abgelehnt'?'Diesmal klappt es leider nicht.':result?.status==='storniert'?'Die Reservierung ist storniert.':'Deine Anfrage ist bei uns.'):'Schön, dass ihr kommt.'}</DialogTitle><DialogDescription>{step===3?'Den aktuellen Status findest du jederzeit über diesen Link.':step===1?'Wann und mit wie vielen Gästen?':'Jetzt brauchen wir noch deine Kontaktdaten.'}</DialogDescription></div>{step!==3&&<div className="reservation-steps"><span className={step===1?'active':''}>1 · Euer Besuch</span><span className={step===2?'active':''}>2 · Kontakt</span></div>}
{step===1&&<><div className="reservation-picker"><div className="date-picker"><span className="field-caption">Welcher Tag darf es sein?</span><Calendar mode="single" locale={de} labels={{labelNext:()=>"Nächster Monat",labelPrevious:()=>"Vorheriger Monat"}} weekStartsOn={1} selected={date} onSelect={setDate} disabled={d=>!validDate(dayKey(d),now)} startMonth={localDate(berlinClock(now).date)} endMonth={new Date(localDate(berlinClock(now).date).getTime()+120*86400000)} className="booking-calendar"/></div><div className="reservation-options"><label className="field">Wie viele Gäste?<Select value={guests} onValueChange={setGuests}><SelectTrigger className="choice"><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:12},(_,i)=><SelectItem key={i} value={String(i+1)}>{i+1} {i===0?'Gast':'Gäste'}</SelectItem>)}</SelectContent></Select></label><p className="muted">Kinder bitte mitzählen.</p><span className="field-caption">Um wie viel Uhr?</span>{slots.length?<RadioGroup value={time} onValueChange={setTime} className="time-slots" aria-label="Gewünschte Uhrzeit">{slots.map(t=><label className={'time-slot '+(time===t?'selected':'')} key={t}><RadioGroupItem value={t} id={'reservation-'+t}/><span>{t}</span></label>)}</RadioGroup>:<p className="muted">Heute sind keine Ankunftszeiten mehr auswählbar. Wähle bitte einen anderen Tag.</p>}<p className="reservation-hint">Die Uhrzeiten sind Wunschzeiten. Deine Anfrage wird von uns persönlich geprüft.</p></div></div><button className="button primary full" disabled={!date||!time} onClick={()=>{setStep(2);setError('')}}>Weiter zu den Kontaktdaten</button></>}
{step===2&&<form onSubmit={submit}><div className="reservation-summary"><CalendarDays size={19}/><div><strong>{dateLabel(key)}</strong><span>{time} Uhr · {guests} {guests==='1'?'Gast':'Gäste'}</span></div><button type="button" className="text-link" onClick={()=>setStep(1)}>Ändern</button></div><div className="contact-fields"><label className="field">Vor- & Nachname<input required autoComplete="name" maxLength={120} value={contact.name} onChange={e=>setContact({...contact,name:e.target.value})}/></label><label className="field">Telefonnummer<input required type="tel" autoComplete="tel" maxLength={25} value={contact.phone} onChange={e=>setContact({...contact,phone:e.target.value})}/></label></div><label className="field">E-Mail-Adresse · {contact.newsletter?'für Eventinfos erforderlich':'optional'}<input type="email" autoComplete="email" required={contact.newsletter} maxLength={180} value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})}/></label><div className="guest-permissions"><label className="check-row"><Checkbox checked={contact.saveGuest} onCheckedChange={v=>setContact({...contact,saveGuest:v===true})}/><span>{RETENTION_TEXT}</span></label><label className="check-row"><Checkbox checked={contact.newsletter} onCheckedChange={v=>setContact({...contact,newsletter:v===true})}/><span>{NEWSLETTER_TEXT}</span></label>{contact.newsletter&&<p className="muted">Wir senden dir eine E-Mail zur Bestätigung. Erst danach erhältst du Eventinfos. {messaging.email?'':'Deine Anmeldung wird bis zum Start der Eventinfos vorgemerkt.'}</p>}{messaging.sms&&<label className="check-row"><Checkbox checked={contact.smsNotify} onCheckedChange={v=>setContact({...contact,smsNotify:v===true})}/><span>Ich möchte den Reservierungsstatus per SMS erhalten.</span></label>}</div><label className="field">Etwas, das wir wissen sollten? · optional<textarea placeholder="Zum Beispiel: Wir benötigen einen Kinderstuhl." maxLength={500} value={contact.note} onChange={e=>setContact({...contact,note:e.target.value})}/></label><p className="muted">Wir verwenden deine Angaben für die Tischanfrage und Rückfragen. Dein Tisch ist reserviert, sobald wir die Anfrage bestätigt haben. Die Bestätigung erscheint hier auf der Seite.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="button primary full" type="submit" disabled={busy}>{busy?'Anfrage wird gesendet …':'Reservierung anfragen'}</button></form>}
{step===3&&result&&<div className="reservation-result" aria-live="polite"><div className={'reservation-status '+(result.status==='bestätigt'?'confirmed':'')} >{result.status==='bestätigt'?<Check/>:<Clock/>}<strong>{result.status==='bestätigt'?'Tisch bestätigt':result.status==='abgelehnt'?'Anfrage abgelehnt':result.status==='storniert'?'Storniert':'Noch nicht bestätigt'}</strong></div>{result.date&&<div className="reservation-summary"><CalendarDays/><div><strong>{dateLabel(result.date)}</strong><span>{result.time} Uhr · {result.guests} {result.guests===1?'Gast':'Gäste'}</span></div></div>}<p>{result.status==='angefragt'?'Wir prüfen, ob wir euch einen passenden Tisch anbieten können. Bitte warte auf die Bestätigung.':result.status==='bestätigt'?'Dein Tisch ist reserviert. Wenn sich bei euch etwas ändert, ruf uns bitte kurz an.':'Ruf uns gerne an, damit wir gemeinsam einen anderen Termin finden.'}</p><p className="muted">Speichere diesen Link oder lass die Seite geöffnet. Der Status aktualisiert sich automatisch. {messaging.sms&&contact.smsNotify?'Den Reservierungsstatus senden wir dir zusätzlich per SMS.':'Die Bestätigung findest du hier auf deiner Reservierungsseite.'}</p>{error&&<p className="error" role="alert">{error}</p>}<div className="reservation-result-actions"><a className="button primary" href="tel:+4915772960906">Paja’s anrufen</a>{result.status!=='angefragt'&&<button className="text-link" onClick={another}>Weitere Tischanfrage</button>}</div></div>}
</DialogContent></Dialog></section>}
