import {sqliteTable,text,integer,index} from "drizzle-orm/sqlite-core";
export const orders=sqliteTable("orders",{id:text("id").primaryKey(),createdAt:integer("created_at").notNull(),name:text("name").notNull(),phone:text("phone").notNull(),plate:text("plate").notNull(),note:text("note").notNull(),items:text("items").notNull(),total:integer("total").notNull(),status:text("status").notNull().default("eingegangen"),pickup:text("pickup").notNull().default(""),invoice:integer("invoice").notNull().default(0),idempotency:text("idempotency").notNull().unique()});
export const settings=sqliteTable("settings",{id:text("id").primaryKey(),value:text("value").notNull()});
export const reservations=sqliteTable("reservations",{id:text("id").primaryKey(),createdAt:integer("created_at").notNull(),date:text("date").notNull(),time:text("time").notNull(),guests:integer("guests").notNull(),name:text("name").notNull(),phone:text("phone").notNull(),note:text("note").notNull(),status:text("status").notNull().default("angefragt"),email:text("email").notNull().default(""),smsNotify:integer("sms_notify").notNull().default(0),idempotency:text("idempotency").notNull().unique()},t=>[index("idx_reservations_date_time").on(t.date,t.time)]);

export const guestProfiles=sqliteTable("guest_profiles",{id:text("id").primaryKey(),contactKey:text("contact_key").notNull().unique(),name:text("name").notNull(),phone:text("phone").notNull(),email:text("email").notNull(),savedAt:integer("saved_at").notNull(),updatedAt:integer("updated_at").notNull(),retention:integer("retention").notNull().default(0),newsletter:text("newsletter").notNull().default("none"),requestedAt:integer("requested_at"),confirmedAt:integer("confirmed_at"),revokedAt:integer("revoked_at"),confirmToken:text("confirm_token").notNull().unique(),unsubscribeToken:text("unsubscribe_token").notNull().unique()});
export const consentEvents=sqliteTable("consent_events",{id:text("id").primaryKey(),guestId:text("guest_id").notNull(),event:text("event").notNull(),time:integer("time").notNull(),text:text("text").notNull(),source:text("source").notNull()});
export const messageJobs=sqliteTable("message_jobs",{id:text("id").primaryKey(),jobKey:text("job_key").notNull().unique(),guestId:text("guest_id"),kind:text("kind").notNull(),channel:text("channel").notNull(),recipient:text("recipient").notNull(),subject:text("subject").notNull(),body:text("body").notNull(),status:text("status").notNull().default("queued"),createdAt:integer("created_at").notNull(),acceptedAt:integer("accepted_at"),sendDay:text("send_day").notNull().default(""),providerId:text("provider_id"),error:text("error").notNull().default("")},t=>[index("idx_message_jobs_status_created").on(t.status,t.createdAt)]);
export const campaigns=sqliteTable("campaigns",{id:text("id").primaryKey(),title:text("title").notNull(),body:text("body").notNull(),createdAt:integer("created_at").notNull(),requestId:text("request_id").notNull().unique()});
