"use client";
import {useEffect,useState} from "react";
import {ShoppingBag,Plus,Minus,Phone,MapPin,Clock,Check,Menu as MenuIcon} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Sheet,SheetContent,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Checkbox} from "@/components/ui/checkbox";
import Reservation from "@/components/reservation";
import {menu,euro,type MenuItem} from "@/lib/menu";
type Line={id:string;name:string;variant:string;options:Record<string,string>;price:number;qty:number;key:string};
const categories=["Schnitzel","Burger","Pizza","Krustino","Currywurst & Klassiker","Salate & Vorspeisen","Fisch","Beilagen & Saucen","Dessert"];
function Choice({value,onChange,options,label}:{value:string;onChange:(s:string)=>void;options:string[];label:string}){return <label className="field">{label}<Select value={value} onValueChange={onChange}><SelectTrigger className="choice"><SelectValue placeholder="Bitte wählen"/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select></label>}
export default function Home(){
const [cfg,setCfg]=useState<Record<string,string>>({}),[cart,setCart]=useState<Line[]>([]),[selected,setSelected]=useState<MenuItem|null>(null),[variant,setVariant]=useState(""),[options,setOptions]=useState<Record<string,string>>({}),[bag,setBag]=useState(false),[mobile,setMobile]=useState(false),[error,setError]=useState(""),[sending,setSending]=useState(false),[invoice,setInvoice]=useState(false),[order,setOrder]=useState<any>(null),[form,setForm]=useState({name:"",phone:"",plate:"",note:""}),[legal,setLegal]=useState<string|null>(null),[requestId,setRequestId]=useState("");
const total=cart.reduce((s,l)=>s+l.price*l.qty,0),count=cart.reduce((s,l)=>s+l.qty,0);
useEffect(()=>{setRequestId(crypto.randomUUID());const load=()=>fetch('/api/config').then(r=>r.ok?r.json():{}).then(setCfg).catch(()=>{});load();const timer=setInterval(load,15000);const hash=location.hash;if(hash.startsWith('#bestellung='))setOrder({id:hash.slice(12),status:'eingegangen'});return()=>clearInterval(timer)},[]);
useEffect(()=>{if(!order?.id)return;const load=()=>fetch('/api/orders/'+order.id).then(r=>r.json()).then((o:any)=>{if(!o.error)setOrder(o)}).catch(()=>{});load();const t=setInterval(load,8000);return()=>clearInterval(t)},[order?.id]);
function configure(i:MenuItem){setSelected(i);setVariant(i.variants[0]?.name||"");setOptions({});setError("")}
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();Promise.resolve(context.registerTool({name:'configure_pajas_dish',description:'Öffnet die sichtbare Auswahl eines Gerichts; legt keine Bestellung an.',inputSchema:{type:'object',properties:{dishId:{type:'string'}},required:['dishId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{const i=menu.find(m=>m.id===input.dishId);if(!i)throw new Error('Unbekanntes Gericht');configure(i);return {dish:i.name,action:'selection_opened'}}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[]);
function add(){if(!selected)return;if(selected.choices.some(c=>!options[c.name])){setError('Bitte alle Optionen auswählen.');return}const price=selected.variants.find(v=>v.name===variant)?.price??selected.price;const key=JSON.stringify([selected.id,variant,options]);setCart(current=>{const existing=current.find(l=>l.key===key);if(existing&&existing.qty>=20)return current;return existing?current.map(l=>l.key===key?{...l,qty:l.qty+1}:l):[...current,{id:selected.id,name:selected.name,variant,options,price,qty:1,key}]});setSelected(null)}
function qty(key:string,delta:number){setCart(c=>c.map(l=>l.key===key?{...l,qty:Math.min(20,l.qty+delta)}:l).filter(l=>l.qty>0))}
async function submit(e:React.FormEvent){e.preventDefault();setError('');setSending(true);try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,invoice,items:cart,requestId})});const o:any=await r.json();if(!r.ok)throw new Error(o.error||'Bitte erneut versuchen.');setOrder({id:o.id,status:'eingegangen',total});location.hash='bestellung='+o.id;setCart([]);setBag(false);setRequestId(crypto.randomUUID())}catch(e){setError(e instanceof Error?e.message:'Bitte erneut versuchen.')}finally{setSending(false)}}
return <>
<header className="header"><a href="#" aria-label="Paja’s Startseite" className="wordmark">PAJA’S<span>RESTAURANT · MAUDACH</span></a><nav className="desktop-nav"><a href="#speisekarte">Speisekarte</a><a href="#wir">Über uns</a><a href="#events">Veranstaltungen</a><a href="#besuch">Dein Besuch</a></nav><div className="nav-actions"><button className="bag-button" onClick={()=>{setError('');setBag(true)}} aria-label={`Warenkorb, ${count} Artikel`}><ShoppingBag size={19}/><span>{count>0?count:'Bestellen'}</span></button><button className="mobile-toggle" onClick={()=>setMobile(!mobile)} aria-label="Navigation öffnen"><MenuIcon/></button></div></header>
{mobile&&<nav className="mobile-nav">{[['Speisekarte','#speisekarte'],['Über uns','#wir'],['Veranstaltungen','#events'],['Dein Besuch','#besuch']].map(([s,h])=><a key={h} href={h} onClick={()=>setMobile(false)}>{s}</a>)}</nav>}
<main>
<section className="hero"><div className="hero-copy"><p className="eyebrow">JASMIN & PATRICE · LUDWIGSHAFEN-MAUDACH</p><h1>Gutes Essen.<br/>Eine schöne<br/><em>Zeit zusammen.</em></h1><p className="intro">Knusprige Schnitzel, Pizza aus unserem Ofen und die Currywurst, mit der alles begann. Willkommen bei Paja’s.</p><div className="hero-actions"><a className="button primary" href="#speisekarte">Speisekarte entdecken</a><a className="text-link" href="#reservieren">Tisch reservieren</a></div><div className="hero-foot"><Clock size={17}/><span>Mo–Fr 17–21 Uhr · Sa–So 17–20 Uhr</span></div></div><div className="hero-image"><img src="/schnitzel.jpg" alt="Frisch angerichtetes Schnitzel mit Pommes aus Paja’s Küche" fetchPriority="high"/><div className="photo-note"><span>AUS UNSERER KÜCHE</span>Hausgemacht. Mit Herz.</div></div></section>
<div className="welcome-line"><span>Ein Restaurant für die ganze Familie.</span><span>Unterer Grasweg 25 · Ludwigshafen-Maudach</span></div>
{order&&<section className="order-tracker wrap" aria-live="polite"><div><p className="eyebrow">DEINE BESTELLUNG · {order.id?.slice(0,8).toUpperCase()}</p><h2>{order.status==='eingegangen'?'Bei uns eingegangen.':order.status==='abgelehnt'?'Leider können wir sie nicht annehmen.':order.status==='bereit'?'Dein Essen ist bereit.':order.status==='abgeholt'?'Danke & guten Appetit!':order.status==='in Zubereitung'?'Wir bereiten dein Essen zu.':'Deine Bestellung ist angenommen.'}</h2><p>{order.pickup?'Abholung: '+order.pickup:'Bitte warte auf unsere Bestätigung und Abholzeit, bevor du losfährst.'}</p><p className="muted">Lass diese Seite geöffnet oder speichere den Link, um den Status zu verfolgen.</p></div><strong>{euro(order.total||0)}</strong></section>}
<section className="menu-section wrap" id="speisekarte"><div className="section-heading"><div><p className="eyebrow">WORAUF HAST DU LUST?</p><h2>Unsere Speisekarte.</h2></div><p>Dein Lieblingsgericht für hier.<br/>Oder für zu Hause.</p></div><div className="ordering-note"><ShoppingBag size={21}/><div><strong>{cfg.accepting==='true'?'Bestellung zur Abholung möglich':'Onlinebestellungen momentan pausiert'}</strong><p>Auswählen · Abholzeit von uns erhalten · Vor Ort bezahlen</p></div><a href="tel:+4915772960906">Fragen? Ruf uns an.</a></div>
<Tabs defaultValue="Schnitzel"><div className="tab-scroll"><TabsList className="menu-tabs" variant="line">{categories.map(c=><TabsTrigger key={c} value={c}>{c}</TabsTrigger>)}</TabsList></div>{categories.map(c=><TabsContent key={c} value={c}><div className="menu-grid">{menu.filter(i=>i.category===c).map(i=><article className="dish" key={i.id}><div><h3>{i.name}</h3><p>{i.description}</p><span className="price">{i.variants.length?'ab ':''}{euro(i.price)}</span></div><button onClick={()=>configure(i)} className="add-dish" disabled={cfg['sold_'+i.id]==='true'} aria-label={i.name+' auswählen'}>{cfg['sold_'+i.id]==='true'?<span>Ausverkauft</span>:<Plus size={21}/>}</button></article>)}</div></TabsContent>)}</Tabs><p className="menu-footnote">Alle Preise in Euro. Pizza gibt es jeden Tag. Bei Allergien oder Unverträglichkeiten sprich bitte vor der Bestellung mit uns: <a href="tel:+4915772960906">01577 2960906</a>.</p></section>
<Reservation/><section className="story" id="wir"><div className="wrap story-inner"><div><p className="eyebrow">PA(TRICE) + JA(SMIN)</p><h2>Zwei Menschen.<br/>Ein Herzensprojekt.</h2></div><div><p>2023 begann Paja’s mit einem kleinen Imbisswagen in Speyer. Aus einer einfachen Idee wurde unser gemeinsamer Weg: ein Ort, an dem Menschen zusammenkommen und sich willkommen fühlen.</p><p>Heute kochen wir für euch in Maudach. Persönlich, mit Leidenschaft und mit der Freude daran, dass aus einem Essen ein schöner Abend wird.</p><p className="signature">Schön, dass du da bist.<span>Jasmin & Patrice</span></p></div></div></section>
<section className="wrap events-section" id="events"><div className="section-heading"><div><p className="eyebrow">ZUSAMMENKOMMEN BEI PAJA’S</p><h2>Mehr als Essen gehen.</h2></div></div><div className="event-grid"><article className="event-card"><div className="date"><strong>18</strong><span>OKTOBER 2026</span></div><p className="eyebrow">SONNTAG · 11–16 UHR</p><h3>Spiele-Tausch<br/>& Tattoos mit Anni.</h3><p>Bring ein Spiel mit, entdecke etwas Neues und finde Mitspieler. Dazu Fineline-Tattoos von Anni und Drinks von der Bar.</p><p className="muted">Im Saal · Die Küche bleibt während des Events geschlossen.</p><a className="text-link" href="mailto:pajas-currywurst@gmx.de?subject=Spiele-Tausch%20am%2018.10.">Fragen zum Event</a></article><article className="event-card celebrations"><p className="eyebrow">DEIN ANLASS. EURE ZEIT.</p><h3>Ein Platz<br/>zum Feiern.</h3><p>Geburtstag, Familienfeier, Taufe oder Firmenabend: Wir besprechen mit dir, was zu deinem Anlass passt – vom Essen bis zum Saal.</p><a className="button outline" href="mailto:pajas-currywurst@gmx.de?subject=Anfrage%20Feier%20bei%20Paja%E2%80%99s">Feier anfragen</a></article></div></section>
<section className="visit wrap" id="besuch"><div><p className="eyebrow">WIR FREUEN UNS AUF DICH.</p><h2>Bis gleich<br/>bei Paja’s.</h2><a className="contact-row" href="https://www.google.com/maps/search/?api=1&query=Unterer+Grasweg+25+67065+Ludwigshafen" target="_blank" rel="noreferrer"><MapPin/>Unterer Grasweg 25<br/>67065 Ludwigshafen-Maudach</a><a className="contact-row" href="tel:+4915772960906"><Phone/>01577 2960906</a><a className="text-link" href="mailto:pajas-currywurst@gmx.de">pajas-currywurst@gmx.de</a></div><div className="hours"><h3>Unsere Öffnungszeiten</h3><div><span>Montag bis Freitag</span><strong>17:00–21:00</strong></div><div><span>Samstag & Sonntag</span><strong>17:00–20:00</strong></div><p>Am Wochenende finden vormittags meist Veranstaltungen statt.</p><a className="button primary" href="#reservieren">Tisch reservieren</a></div></section>
</main><footer><div className="footer-brand" role="img" aria-label="Paja’s – das Restaurant für die ganze Familie"/><div><a href="https://www.instagram.com/pajas.restaurant/" target="_blank" rel="noreferrer">Instagram</a><button onClick={()=>setLegal('Kontakt')}>Kontakt</button><button onClick={()=>setLegal('Datenschutz')}>Datenschutz</button><a href="/team">Teambereich</a><span>© {new Date().getFullYear()} Paja’s</span></div></footer>
{count>0&&!bag&&<button className="floating-bag" onClick={()=>{setError('');setBag(true)}}><ShoppingBag size={18}/>Warenkorb · {count}<strong>{euro(total)}</strong></button>}
<Dialog open={!!selected} onOpenChange={o=>{if(!o)setSelected(null)}}><DialogContent className="dish-dialog"><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>{selected?.description||'Stelle dein Gericht zusammen.'}</DialogDescription>{selected?.variants.length? <Choice label="Variante" value={variant} onChange={setVariant} options={selected.variants.map(v=>v.name)}/>:null}{selected?.choices.map(c=><Choice key={c.name} label={c.name+' · Pflichtwahl'} value={options[c.name]||''} options={c.options} onChange={s=>setOptions(o=>({...o,[c.name]:s}))}/>)}{error&&<p className="error" role="alert">{error}</p>}<button className="button primary full" onClick={add}>Zum Warenkorb · {euro(selected?.variants.find(v=>v.name===variant)?.price??selected?.price??0)}</button></DialogContent></Dialog>
<Sheet open={bag} onOpenChange={setBag}><SheetContent className="cart-panel"><SheetTitle>Deine Bestellung.</SheetTitle><SheetDescription>Zur Abholung bei Paja’s · Bezahlung vor Ort</SheetDescription><div className="cart-scroll">{!cart.length?<div className="empty"><ShoppingBag size={38}/><h3>Noch ein bisschen Hunger?</h3><p>Wähle dein Lieblingsgericht aus unserer Speisekarte.</p><button className="button primary" onClick={()=>{setBag(false);document.getElementById('speisekarte')?.scrollIntoView()}}>Zur Speisekarte</button></div>:<><div className="cart-lines">{cart.map(l=><article key={l.key}><div><h3>{l.name}</h3><p>{[l.variant,...Object.values(l.options)].filter(Boolean).join(' · ')}</p><div className="quantity"><button type="button" aria-label={l.name+' weniger'} onClick={()=>qty(l.key,-1)}><Minus size={16}/></button><span>{l.qty}</span><button type="button" aria-label={l.name+' mehr'} onClick={()=>qty(l.key,1)} disabled={l.qty>=20}><Plus size={16}/></button></div></div><strong>{euro(l.price*l.qty)}</strong></article>)}</div><div className="total"><span>Gesamt</span><strong>{euro(total)}</strong></div><form onSubmit={submit}><label className="field">Vor- & Nachname<input required autoComplete="name" maxLength={120} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field">Handynummer für Rückfragen<input required type="tel" autoComplete="tel" maxLength={25} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="field">Kennzeichen · optional<input maxLength={20} placeholder="Für die Abholung am Auto" value={form.plate} onChange={e=>setForm({...form,plate:e.target.value})}/></label><label className="field">Nachricht an die Küche · optional<textarea maxLength={800} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><label className="check-row"><Checkbox checked={invoice} onCheckedChange={v=>setInvoice(v===true)}/>Rechnung gewünscht</label><p className="muted">Wir bestätigen deine Bestellung und nennen dir hier die Abholzeit. Deine Angaben verwenden wir zur Bearbeitung und für Rückfragen.</p>{error&&<p role="alert" className="error">{error}</p>}<button className="button primary full" disabled={sending||cfg.accepting!=='true'} type="submit">{sending?'Wird gesendet …':cfg.accepting==='true'?'Zahlungspflichtig bestellen · '+euro(total):'Bestellungen momentan pausiert'}</button></form></>}</div></SheetContent></Sheet>
<Dialog open={!!legal} onOpenChange={o=>{if(!o)setLegal(null)}}><DialogContent><DialogTitle>{legal}</DialogTitle><DialogDescription>{legal==='Kontakt'?'Paja’s Restaurant · Familie Wehrlé':'Hinweise zu dieser Bestellseite'}</DialogDescription>{legal==='Kontakt'?<p>Unterer Grasweg 25, 67065 Ludwigshafen<br/>01577 2960906<br/>pajas-currywurst@gmx.de</p>:<div><p>Bei einer Bestellung speichern wir den eingegebenen Namen, die Telefonnummer, gegebenenfalls das Kennzeichen, die Nachricht und die ausgewählten Gerichte. Bei Tischanfragen speichern wir außerdem Datum, Uhrzeit, Personenzahl und den Bearbeitungsstatus. Wenn du es auswählst, speichern wir deine Kontaktdaten für künftige Besuche und dokumentieren deine Anmeldung für Eventinfos. Für eine ausgewählte SMS-Benachrichtigung und E-Mails nutzen wir nach Aktivierung den Versanddienst Brevo. Eventinfos erhältst du erst nach Bestätigung deiner E-Mail-Adresse; du kannst dich über den Link in jeder Eventmail abmelden. Du kannst dich mit Fragen oder einem Widerruf auch an uns wenden. Wir nutzen diese Angaben zur Bearbeitung der Bestellung und für Rückfragen.</p><p>Der Teambereich verwendet ein notwendiges, geschütztes Zugangscookie. Wir setzen auf dieser Seite keine Analyse- oder Werbetracker ein. Instagram und Karten öffnen als externe Links.</p><p>Kontakt für Fragen: pajas-currywurst@gmx.de.</p></div>}</DialogContent></Dialog>
</>}
